% Two-dimensional discrete wavelet transform.
%
% INPUT
% x    - One dimensional representation of an N × N matrix 
% mode - Boolean. If mode == 1, the DWT with Haar wavelet is applied,
%        otherwise the conjugate transpose will be used
% wname - wavelet name string for wavedec2 and waverec2 (Wavelet Toolbox)
% nres - number of levels
% bdry - wavelet mode string for dwtmode (Wavelet Toolbox)
% S    - Bookkeeping matrix generated by wavedec2 (Wavelet Toolbox)
% N    - Size of the original N × N image
%
% OUTPUT
% The result of the operator applied to x.  
%
function y = h_op_wavelet_2d(x, mode, wname, nres, bdry, S, N)
    
    if (~isvector(x))
        error('Input is not a vector');
    end
    
    dwtmode(bdry, 'nodisp')
    
    if (mode == 1)
        X = reshape(x, [N N]);
        [y,~] = wavedec2(X,nres,wname);
        
    else % adjoint
        
        y = waverec2(x,S,wname);  
        
    end
end

